#!/usr/bin/env bash
# If the 1th or 2th parameter is unset exit
if [[ -z $1 ]]; then
	echo "No name to compile"
	exit 1
else
	file_x=$1
fi
if [[ -z $2 ]]; then
	echo "No .c files"
	exit 1
else
	all_param=$@
fi

# If there is multiple .c files
file_c="${all_param##$file_x }"

if [[ $(which entr) == "" ]]; then
	echo "Need to install entr"
	echo "https://github.com/clibs/entr"
	exit 1
fi
ls | entr -c sh -c "gcc -o $file_x $file_c && ./$file_x"
