#!/usr/bin/env bash

set -eou pipefail

SCRIPT_FILE="$(realpath "$0")"

declare -r WGET_OUTPUT="-q --show-progress"

declare -r PREFIX="$HOME/.local"
declare -r OBSIDIAN="$PREFIX/obsidian-app"

declare -r NAME="Obsidian-App"
declare -r ICON="$OBSIDIAN/icon.svg"
declare -r CURRENT_VERSION_FILE="$OBSIDIAN/current-version.txt"
declare -r APP_IMAGE="$OBSIDIAN/Obsidian.AppImage"
declare -r DESKTOP="$PREFIX/share/applications/obsidian-app.desktop"

get_latest_repo_version() {
	local git_user_name="$1"
	local git_repo="$2"
	local tag_name_pre="${3:-"v"}"

	curl -s "https://api.github.com/repos/${git_user_name}/${git_repo}/releases/latest" | \
		grep -oP "\"tag_name\": \"${tag_name_pre}\K[0-9.]+" | \
		head -1
}

check_dependencies() {
	if command -v curl &>/dev/null && command -v wget &>/dev/null; then
		return
	fi

	echo "Need to install the dependencies"
	show_help
	exit 3
}

init_folders() {
	if [[ ! -d $OBSIDIAN ]]; then
		mkdir -p "$OBSIDIAN"
	fi

	if [[ ! -d $PREFIX/share/applications ]]; then
		mkdir -p "$PREFIX/share/applications"
	fi
}

get_icon () {
	if [[ -f "$ICON" ]]; then
		echo "$ICON is already downloaded"
		return
	fi

	echo -e "\tDownloading $ICON"
	wget "$WGET_OUTPUT" -O "$ICON" "https://obsidian.md/images/obsidian-logo-gradient.svg"
}

get_obsidian() {
	check_dependencies
	init_folders

    local latest_version current_version
	latest_version="$(get_latest_repo_version "obsidianmd" "obsidian-releases" "v")"
	current_version="$(cat "$CURRENT_VERSION_FILE" 2>/dev/null)"

	if [[ $latest_version == "$current_version" ]]; then
		echo -e "\tAlready update"
		return
	fi
	echo -e "\tInstalling Obsidian"

	get_icon

	wget "$WGET_OUTPUT" -O "$APP_IMAGE" "https://github.com/obsidianmd/obsidian-releases/releases/download/v$latest_version/Obsidian-$latest_version.AppImage"
	chmod u+x "$APP_IMAGE"

	create_desktop

	echo "$latest_version" > "$CURRENT_VERSION_FILE"
}

create_desktop() {
	echo -e "\tCreating $DESKTOP"
	cat > "$DESKTOP" << EOF
[Desktop Entry]
Type=Application
Name=$NAME
Exec=$SCRIPT_FILE run
Icon=$ICON
Terminal=false
EOF

	chmod u+x "$DESKTOP"
}

get_user_choice() {
	local message="$1"
	local input

	while true; do
		read -r -p "$message [Y/N] " input
		case "$input" in
			[Yy]) return 0;;
			[Nn]) return 1;;
			*) echo "Press \"Y\" or \"N\""
		esac
	done
}

show_help() {
	cat << EOF
Install the official Obsidian AppImage
Usage: obsidian-app [ARGUMENTS]

ARGUMENTS:
        run               Run Obsidian
        update/install    Update Obsidian
        remove            Remove Obsidian
        help              Show help

Dependencies:
        curl, wget

Examples:
        obsidian-app run
        obsidian-app update
EOF
}

if [[ -z ${1+x} ]]; then
	echo "Error: Need at least one argument"
	show_help
	exit 1
fi

case "$1" in
	run)
		get_obsidian
		echo "Running \"$APP_IMAGE\""
		nohup "$APP_IMAGE" &>/dev/null
		;;
	install|update) get_obsidian;;
	help) show_help;;
	remove)
		if get_user_choice "Remove $OBSIDIAN?"; then
			rm -rf "$OBSIDIAN"
		fi
		if get_user_choice "Remove $DESKTOP?"; then
			rm -f "$DESKTOP"
		fi
		;;
	*)
		echo "Error: Unknown argument \"$1\""
		show_help
		exit 2
		;;
esac
