#!/usr/bin/env bash

set -eou pipefail

# ------------------------------------------------------------
# Initial setup
# ------------------------------------------------------------

command_exists()
{
    command -v "$1" &>/dev/null
}

if [[ -t 1 ]]; then
    if tput colors &>/dev/null; then
        RED="$(tput setaf 1)"
        BOLD="$(tput bold)"
        RESET="$(tput sgr0)"
	else
        RED=""
        BOLD=""
        RESET=""
    fi
fi

error()
{
    local msg="$1"
    local code="${2:-1}"

    local prefix="ERROR: "

	printf '%s%s%s%s%s\n' "$BOLD" "$RED" "$prefix" "$RESET" "$msg" >&2

    exit "$code"
}

if ! command_exists tmux; then
	error "Tmux executable not found" 3
fi

# ------------------------------------------------------------
# Global variables
# ------------------------------------------------------------

readonly -a IGNORE_PARENT=("$HOME" "/" "$HOME/.config")
readonly -a WINDOW_NAMES=("code" "run")
readonly -a HOT_FOLDERS=("$HOME/nixos" "$HOME/.config/awesome" "$HOME/.config/nvim")
readonly RECURSIVE_SEARCH_FOLDERS="$HOME/code"

# ------------------------------------------------------------
# Functions
# ------------------------------------------------------------

show_help()
{
	cat <<- EOF
	Usages:
		tmux-manager                    [Fzf mode]
		tmux-manager .                  [Current directory]
		tmux-manager path/to/directory
		tmux-manager -p                 [Prompt mode]
		tmux-manager -h                 [This help]
EOF
}

normalize_dots()
{
	local string="$1"

	normalize="${string//./_}"

	echo "$normalize"
}

check_if_nixos()
{
    if [[ -r /etc/os-release ]]; then
        if grep -q "ID=nixos" /etc/os-release; then
            return 0
        fi

        return 1
    fi

    return 1
}

nix_shell_hook()
{
	local session_name="$1"
	local session_path="$2"

    if ! check_if_nixos; then
        return 0
    fi

    local nix_shell_cmd=""

    if [[ -f "$session_path/shell.nix" ]]; then
        nix_shell_cmd="nix-shell"
    elif [[ -f "$session_path/flake.nix" && ! -f "$session_path/configuration.nix" ]]; then
        nix_shell_cmd="nix develop"
    else
        return 0
    fi

	local i
    for i in "${!WINDOW_NAMES[@]}"; do
		local win="${WINDOW_NAMES[i]}"
        local index=$(( i + 1 ))

        if tmux list-windows -t "$session_name" 2>/dev/null | grep -q "$win"; then
            tmux send-keys -t "$session_name:$win" "$nix_shell_cmd" C-m
        fi
    done
}

create_session_windows()
{
	local session_name="$1"
	local session_path="$2"
	
	local i
    for i in "${!WINDOW_NAMES[@]}"; do
		local win="${WINDOW_NAMES[i]}"
        local index=$(( i + 1 ))

        if ! tmux list-windows -t "$session_name" 2>/dev/null | grep -q "$win"; then
            tmux new-window -c "$session_path" -t "$session_name:$index" -d -n "$win" &>/dev/null || tmux rename-window -t "$session_name:$index" "$win"
        fi
    done

	nix_shell_hook "$session_name" "$session_path"
}

normalize_session_path()
{
	local session_path="$1"

	local normalized

	normalized="$(realpath "$session_path")"

	echo "$normalized"
}

# Get a session name with "parent/folder" format
get_session_name()
{
    local session_path="$1"

    readonly separator="/"

    local parent name
    parent="$(basename "$(dirname "$session_path")")"
    name="$(basename "$session_path")"

	final_name="$parent$separator$name"
	for ignore in "${IGNORE_PARENT[@]}"; do
		if [[ "$parent" == "$(basename "$ignore")" ]]; then
			final_name="$name"
			break
		fi
	done

    normalize_dots "$final_name"
}

get_session_data_fzf()
{
    if ! command_exists fzf; then
        show_help
        error "Fzf executable not found. Try using a option above." 3
    fi

	local session_data
	session_data=$(
		{
			echo "--- Tmux Sessions ---"
			tmux list-sessions -F "#{session_name}" 2>/dev/null

			echo "--- Hot Directories ---"
            for folder in "${HOT_FOLDERS[@]}"; do
                echo "$folder"
            done

			echo "--- Project Directories ---"
			find "$RECURSIVE_SEARCH_FOLDERS" -mindepth 1 -maxdepth 2 -type d 2>/dev/null
		} | fzf --prompt="Select a directory or session: " \
            --header-first \
            --layout "reverse"
	)

	if [[ -z "$session_data" ]]; then
        error "No selection made."
	fi

	if [[ "$session_data" == ---* ]]; then
		return 2
	fi

	echo "$session_data"
}

# FIX: This function should validate either a tmux session name or a folder path
get_session_data_prompt()
{
	local input_path session_data
	while :
	do
		read -r -e -p "Enter a directory/session: [None for fzf] " input_path

		if [[ -z $input_path ]]; then
			session_data="$(get_session_data_fzf)"
			break
		fi

        session_data="$(realpath -m "${input_path/#\~/"$HOME"}")"

		echo "Please try again" >&2
	done

	echo "$session_data"
}

# ------------------------------------------------------------
# User interaction
# ------------------------------------------------------------

# Can be either a tmux session name or a folder path
SESSION_DATA=""

if [[ $# -eq 0 ]]; then
	SESSION_DATA="$(get_session_data_fzf)"
elif [[ $# -eq 1 ]]; then
	if [[ $1 == -p ]]; then
		echo "Fixing this"
		# SESSION_DATA="$(get_session_data_prompt)"
	elif [[ $1 == -h ]]; then
		show_help
		exit 0
	elif [[ $1 == . ]]; then
		SESSION_DATA="$PWD"
	else
		SESSION_DATA="$1"
	fi
else
	show_help
	error "More than 2 arguments"
fi

SESSION_PATH=""
SESSION_NAME=""

# TODO: This if statment should be in a function
if tmux has-session -t "$SESSION_DATA" &>/dev/null; then
	SESSION_PATH="NONE"
	SESSION_NAME="$SESSION_DATA"
elif [[ -d "$SESSION_DATA" ]]; then
	SESSION_PATH="$(normalize_session_path "$SESSION_DATA")"
	SESSION_NAME="$(get_session_name "$SESSION_PATH")"
else
	error "No session or folder named \"$SESSION_DATA\" exists"
fi

# ------------------------------------------------------------
# Tmux session/window creation
# ------------------------------------------------------------

if ! tmux has-session -t "$SESSION_NAME" &>/dev/null; then
	tmux new-session -d -s "$SESSION_NAME" -c "$SESSION_PATH"
	create_session_windows "$SESSION_NAME" "$SESSION_PATH"
fi

if [[ -z ${TMUX+x} ]]; then
	tmux attach-session -t "$SESSION_NAME"
else
	tmux switch-client -t "$SESSION_NAME"
fi
