#!/usr/bin/env bash

set -eou pipefail

# ------------------------------------------------------------
# Initial setup
# ------------------------------------------------------------

command_exists()
{
    command -v "$1" &>/dev/null
}

if [[ -t 2 && -z "${NO_COLOR:-}" ]]; then
    if command_exists tput && tput colors &>/dev/null; then
        RED="$(tput setaf 1)"
        BOLD="$(tput bold)"
        RESET="$(tput sgr0)"
    fi
fi

error()
{
    local msg="$1"
    local code="${2:-1}"

    local error_string="ERROR"

    if [[ -n "${RED:-}" ]]; then
        printf '%s%s%s:%s %s\n' "$BOLD" "$RED" "$error_string" "$RESET" "$msg" >&2
    else
        printf '%s: %s\n' "$error_string" "$msg" >&2
    fi

    exit "$code"
}

if ! command_exists tmux; then
	error "Tmux executable not found" 3
fi

# ------------------------------------------------------------
# Global variables
# ------------------------------------------------------------

RECURSIVE_SEARCH_FOLDERS="$HOME/code"
HOT_FOLDERS=("$HOME/nixos" "$HOME/.config/awesome" "$HOME/.config/nvim")
WINDOW_NAMES=("code" "run")

# ------------------------------------------------------------
# Functions
# ------------------------------------------------------------

show_help()
{
	cat <<- EOF
	Usages:
		tmux-manager [Fzf mode]
		tmux-manager . [Current directory]
		tmux-manager path/to/directory
		tmux-manager -p [Prompt mode]
		tmux-manager -h [This help]
EOF
}

check_if_nixos()
{
    if [[ -r /etc/os-release ]]; then
        if grep -q "ID=nixos" /etc/os-release; then
            return 0
        fi

        return 1
    fi

    return 1
}

nix_shell_hook()
{
	local session_name="$1"
	local session_path="$2"

    if ! check_if_nixos; then
        return 0
    fi

    local nix_shell_cmd=""

    if [[ -f "$session_path/shell.nix" ]]; then
        nix_shell_cmd="nix-shell"
    elif [[ -f "$session_path/flake.nix" && ! -f "$session_path/configuration.nix" ]]; then
        nix_shell_cmd="nix develop"
    else
        return 0
    fi

    for index in "${!WINDOW_NAMES[@]}"; do
        local key=$(( index + 1 ))
        local win="${WINDOW_NAMES[index]}"

        if tmux list-windows -t "$session_name" 2>/dev/null | grep -q "$win"; then
            tmux send-keys -t "$session_name:$win" "$nix_shell_cmd" C-m
        fi
    done
}

create_session_windows()
{
	local session_name="$1"
	local session_path="$2"
	
    for index in "${!WINDOW_NAMES[@]}"; do
        local key=$(( index + 1 ))
        local win="${WINDOW_NAMES[index]}"

        if ! tmux list-windows -t "$session_name" 2>/dev/null | grep -q "$win"; then
            tmux new-window -c "$session_path" -t "$session_name:$key" -d -n "$win" &>/dev/null || tmux rename-window -t "$session_name:$key" "$win"
        fi
    done

	nix_shell_hook "$session_name" "$session_path"
}

get_session_name()
{
	local session_path="$1"

    session_path="${session_path%/}"

	basename "$session_path" | tr . _
}

validate_session_path()
{
	local session_path="$1"

	if [[ -d "$session_path" ]]; then
		return 0
	fi

    local session_name
	session_name="$(get_session_name "$session_path")"

	if tmux has-session -t "$session_name" 2>/dev/null; then
		return 0
	fi

	error "The directory \"$session_path\" or session \"$session_name\" does not exist"
}

get_session_fzf()
{
    if ! command_exists fzf; then
        show_help
        error "Fzf executable not found. Try using a option above." 3
    fi

	local session_path
	session_path=$(
		{
			echo "--- Tmux Sessions ---"
			tmux list-sessions -F "#{session_name}" 2>/dev/null

			echo "--- Hot Directories ---"
            for folder in "${HOT_FOLDERS[@]}"; do
                echo "$folder"
            done

			echo "--- Project Directories ---"
			find "$RECURSIVE_SEARCH_FOLDERS" -mindepth 1 -maxdepth 2 -type d 2>/dev/null
		} | fzf --prompt="Select a directory or session: " \
            --header-first \
            --layout "reverse"
	)

	if [[ -z "$session_path" ]]; then
        error "No selection made."
	fi

	if [[ "$session_path" == ---* ]]; then
		return 2
	fi

	if ! validate_session_path "$session_path"; then
		return 3
	fi

	echo "$session_path"
}

input_work_folder()
{
	local input_path session_path
	while :
	do
		read -r -e -p "Enter a directory/session: [None for fzf] " input_path

		if [[ -z $input_path ]]; then
			session_path="$(get_session_fzf)"
			break
		fi

        session_path="$(realpath -m "${input_path/#\~/"$HOME"}")"

		if validate_session_path "$session_path"; then
			break
		fi

		echo "Please try again" >&2
	done

	echo "$session_path"
}

# ------------------------------------------------------------
# User interaction
# ------------------------------------------------------------

SESSION_PATH=""
SESSION_NAME=""

if [[ $# -eq 0 ]]; then
	SESSION_PATH="$(get_session_fzf)"
elif [[ $# -eq 1 ]]; then
	if [[ $1 == -p ]]; then
		SESSION_PATH="$(input_work_folder)"
	elif [[ $1 == -h ]]; then
		show_help
		exit 0
	elif [[ $1 == . ]]; then
		SESSION_PATH="$PWD"
	else
		if ! validate_session_path "$1"; then
			show_help
			exit 2
		fi

		SESSION_PATH="$1"
	fi
else
	show_help
	error "More than 2 arguments"
fi

SESSION_PATH="${SESSION_PATH%/}"

SESSION_NAME="$(get_session_name "$SESSION_PATH")"

# ------------------------------------------------------------
# Tmux session/window creation
# ------------------------------------------------------------

if  ! tmux list-sessions &>/dev/null || \
	! tmux has-session -t "$SESSION_NAME" &>/dev/null
then
	tmux new-session -d -s "$SESSION_NAME" -c "$SESSION_PATH"
	create_session_windows "$SESSION_NAME" "$SESSION_PATH"
fi

if [[ -z ${TMUX+x} ]]; then
	tmux attach-session -t "$SESSION_NAME"
else
	tmux switch-client -t "$SESSION_NAME"
fi
