#!/bin/bash

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Variables
export VIMCONF="$HOME/.vim/config"
export EDITOR=vim

if command -v alacritty > /dev/null 2>&1;
then
  export TERM=alacritty
fi
