import = [
    "~/.config/alacritty/themes/argonaut.toml"
]

#[shell]
#program = "/bin/zsh"
#args = ["-l"]

#[env]
#TERM = xterm-256color

[font]
normal = { family = "UbuntuMono Nerd Font Mono", style = "Regular" }
